### ISSUE TITLE
Fails on many tests in updated Test262 suite

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#1]
This parser fails on many tests in the updated Test262 suite, and the AnnexB 3.5 semantic have been simplified. Also cases like `function foo(package) { "use strict"; }` fails to throw an error - both for functions, arrows and async arrows where the reserved words are in the arg list and the directive come last in the function body. Same with legacy octals.
I couldn't either get it to throw on duplicate async functions and generator functions unless I parsed in strict mode. As in the Test262 suite it should fail if in strict mode, async context, non-simple args etc.

**Comment by donnagf** [comment]
Closing as it seems irrelevant.

**Comment by pvdz** [comment]
Not sure about 262, although I do want to strive to pass it. The reserved keyword should trigger an error, that is relevant. Thanks!

**Comment by pvdz** [comment]
@donnagf what exactly did you mean with "octals"? As far as I remember you can't have any default when the function opts in to strict mode. Were you talking about octals in param defaults? In which case those are automatically illegal because defaults are on a whole (that'll properly throw now), or were you talking about something else?

**Comment by donnagf** [comment]
Something like this, but also nested functions with octals. And same for future reserved words after what I could read from the specs.

```js
function foo() { "use strict"; 00004; }

function 00004() { "use strict"; 00004; }

function foo(001, 003) { "use strict"; }
```

**Comment by pvdz** [comment]
Oh hm, the `08` number thing might actually be something I overlooked. But it's been a long time since I wrote the tokenizer so perhaps I have. By the way feel free to just spin up new tickets for these things. You can use the `[ ] - ``code`` ` syntax to make checklists so I can work through them, when I have the time.

**Comment by pvdz** [comment]
Filed #15 for the octal cases

**Comment by pvdz** [comment]
Closing this as I think the actual cases were fixed. Please report the other stuff in new tickets with concrete cases if you have them. You're doing great :D
