### ISSUE TITLE
for-await

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#10]
`for await` should only be valid in async context. This 'check' is missing. And this tests need investigation.

- [ ] `async function f() { for await ([a] = 1 of []); }`

- [ ] `async function f() { for await ([a = 1] = 1 of []); }`

- [ ] `async function f() { 'use strict'; for await ({a} = 1 of []); }`

- [ ] `async function * f() { for await ({a: a} = 1 of []); }`

- [ ] `async function * f() { for await ({0: a} = 1 of []); }`

- [ ] `async function * f() { for await ({0: a = 1} = 1 of []); }`

**Comment by pvdz** [comment]
All these cases are passing now, thanks :)

**Comment by pvdz** [comment]
All these cases are actually incorrect because the assignment left of `in` and `of` is always illegal with a pattern. I was misinterpreting the wording in the spec which says "if it's an object, then it must cover a Pattern", which does not imply that any Pattern is valid. It must still first cover an object or array, which by themselves do not allow an assignment to follow.

Just saying for the sake of history. Hello from the past!
