### ISSUE TITLE
Patterns in func calls should throw an error, even if func is called `async`

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#14]
(Edit:)

- [x] `foo({a=1})`
- [x] `foo({a=1}. {b=2}, {c=3} = {})`
- [x] `foo({c=3} = {})`
- [x] `async({a=1})`
- [x] `async({a=1}. {b=2}, {c=3} = {})`
- [x] `async({c=3} = {})`

Original;

- [x] `typeof async({a = 1});`
- [x] `typeof async({a = 1}, {b = 2}, {c = 3} = {});`
- [x] `typeof async({a = 1}, {b = 2} = {}, {c = 3} = {});`

**Comment by pvdz** [comment]
Your case seems to be a little conflated. It is totally fine to do `typeof async()`. The problem is that `{a = 1}` is not a valid object literal expression, only a vaid pattern. And since you can't use a pattern in a function call, all these examples are supposed to fail (and they don't so I'll fix that). I'm updating the original report to reflect this.

**Comment by pvdz** [comment]
Actually, the problem is that `async` is going through a slightly different path which is not invalidating args if they were destructuring only (because they might be valid in case of an async arrow so this validation step should happen later, except that it doesn't).

**Comment by pvdz** [comment]
Fixed, thank you :)

**Comment by donnagf** [comment]
@pvdz No problem, but maybe you should write a test for this one? `async(a,)`.

**Comment by pvdz** [comment]
Will do

**Comment by pvdz** [comment]
Fixed, thanks :)
