### ISSUE TITLE
Doesn't parse arrows correctly

### ISSUE THREAD

**Issue by donnagf** [pvdz/zeparser3#3]
@pvdz  Your arrow parsing is invalid. Try this valid programs

```js
() => a
() => {}
() => {}
```

and 

```js
() => {}
(() => {})().abc.call("Hello")
```

```js
foo => bar
() => {}
```

Same with async equalents! And also other combinations!

**Comment by pvdz** [comment]
Ooooh, ASI problems. Thanks for bringing them to my attention. I'll try to have a fix this weekend :)

Can I ask what you were using the parser for?

**Comment by pvdz** [comment]
Wait, actually. Are you sure they're illegal? Why do you expect ASI to be applied?
```
() => a
() => {}
```
is
```
() => a() => {}
```
which, as you can guess, is fine up to parsing the second arrow. The parser is not meant to backtrack, it will keep on parsing until the next token cannot be consumed. In this case, I believe my parser is doing the correct thing. Other parsers agree, as you can check on astexplorer.net

So if this program is supposed to be legal, can you tell me why? Why should ASI be applied to these cases?

**Comment by donnagf** [comment]
Hi. I started out with an attempt to create a React app for mobile devices, and come across your parser because you are working there :) And I'm not so familiar with open source code so my guess was that you + fb = stable code and good match. From there I went on with trying to create another mobile app with your parser, but ran into this issues.

I also ran into a few other issues, but closed the issues because I would avoid bothering you :) You can re-open them too if you want!

Anyway! Great work with this parser! Do you plan to implement eager and lazy parsing fully? As I can see from the source code I think you already are doing some lazy parsing? 
For my examples. I wrote them from my head after discovering the issues, and yes you are right regarding the last one. It should actually fail in AST explorer as seen [here](https://astexplorer.net/#/gist/888f7548bb4a396d15ba93fe8cfe0d7b/9b75c6c5df4d0a72980fd3ee1def9fcfaccb75ca)

After discovering this issues I was just playing around with your parser and discovered that I ran into issues with deeply nested async arrows as well as that Object spread shouldn't allow bindings at all. But your's doesn't fail on this as well `({foo: {x:y} += x})`, and this one should parse if you compare against V8.

**Comment by donnagf** [comment]
@pvdz I looked into this some more...

```js
() => a() => {} // Invalid

// Should be valid
() => a 
() => {}

// Above equal to -also valid

function a() {}
function b() {}

// Odd case
function a() {} function b() {} // valid!
```

**Comment by pvdz** [comment]
> Do you plan to implement eager and lazy parsing fully?

No concrete plans here. I think the parser is eager right now?

The only plan I have here is to make it error resilient. So if it hits a parser error it should emit an error token and attempt to continue parsing.

> But your's doesn't fail on this as well `({foo: {x:y} += x})`, and this one `[(a = 0)] = 1` should parse if you compare against V8.

So from the top of my head, `({foo: {x:y} += x})` should be illegal because destructuring can only be an assignment. ([Example on astexplorer](https://astexplorer.net/#/gist/e1246ed59ee8628f4ea9903e2dd9339d/4ae1e7f0e4438a725c5f3990d04369e8bd4fd168) to confirm this). Looks like zeparser is overaccepting this case.

Then `[(a = 0)] = 1` is trickier because of edge cases with parenthesis and destructuring. I would not expect this to be legal, but [Babel thinks it is](https://astexplorer.net/#/gist/e1246ed59ee8628f4ea9903e2dd9339d/c5b1f7c3da67336d0c80effa74898837e91304ca) so I'll have to investigate why (although [Acorn does think it's illegal](https://astexplorer.net/#/gist/e1246ed59ee8628f4ea9903e2dd9339d/e0ef916e94744647eb1d5a0f95ab3b74c505fc49)...). Will dig into this one.

> // Above equal to -also valid

Why do you think these are the same? Arrows behave different to function declarations when it comes to ASI. A function declaration is explicitly specced not to require a trailing semi colon. So `function f(){}function g(){}` is legit on the same line where `()=>{}()=>{}` is not. For the same reason they are not the same on separate lines. Can you elaborate why you think the arrows should be valid on sepate lines?

> Do you plan to add location tracking?

Yeah :)

Thanks for the feedback. I appreciate it and will work to improve on the highlighted cases and whatever else surfaces :)

**Comment by pvdz** [comment]
I traced the spec to confirm whether `[(a=0)]=1` is legit or not:

- https://tc39.github.io/ecma262/#sec-destructuring-assignment-static-semantics-early-errors
  - `DestructuringAssignmentTarget: LeftHandSideExpression`
  - > It is a Syntax Error if LeftHandSideExpression is either an ObjectLiteral or an ArrayLiteral and if LeftHandSideExpression is not covering an AssignmentPattern.
  - so, is `[(a = 0)]` covering an assignment pattern..?
- https://tc39.github.io/ecma262/#prod-AssignmentPattern
- https://tc39.github.io/ecma262/#prod-ArrayAssignmentPattern
- https://tc39.github.io/ecma262/#prod-AssignmentElementList
- https://tc39.github.io/ecma262/#prod-AssignmentElisionElement
- https://tc39.github.io/ecma262/#prod-AssignmentElement
- https://tc39.github.io/ecma262/#prod-DestructuringAssignmentTarget
  - > LeftHandSideExpression[?Yield, ?Await]
- https://tc39.github.io/ecma262/#sec-destructuring-assignment-static-semantics-early-errors
  - > DestructuringAssignmentTarget: LeftHandSideExpression
- https://tc39.github.io/ecma262/#sec-semantics-static-semantics-assignmenttargettype
  - > It is a Syntax Error if `LeftHandSideExpression` is neither an `ObjectLiteral` nor an `ArrayLiteral` and `AssignmentTargetType(LeftHandSideExpression)` is not simple.
- https://tc39.github.io/ecma262/#sec-semantics-static-semantics-assignmenttargettype
  - `PrimaryExpression: CoverParenthesizedExpressionAndArrowParameterList`
  - > Let expr be `CoveredParenthesizedExpression` of CoverParenthesizedExpressionAndArrowParameterList.
  - > Return AssignmentTargetType of expr.
  - The `CoveredParenthesizedExpression` of `(a = 1)` is:
- https://tc39.github.io/ecma262/#sec-grouping-operator-runtime-semantics-namedevaluation
  - `ParenthesizedExpression: (Expression)`
  - > Return the result of evaluating `Expression`. This may be of type `Reference`.
  - In this case `a  = 0` returns a `Reference`
  - The assignment is an `AssignmentExpression`: https://tc39.github.io/ecma262/#prod-AssignmentExpression
- https://tc39.github.io/ecma262/#sec-grouping-operator-static-semantics-assignmenttargettype
  - > Return `AssignmentTargetType` of `Expression`.
  - (Above we concluded the expression was an assignment, so that's `a = 0`)
  - The last step is to verify that this is in fact a simple assignment
- https://tc39.github.io/ecma262/#sec-assignment-operators-static-semantics-assignmenttargettype
  - `AssignmentExpression: LeftHandSideExpression=AssignmentExpression`
    - > Return invalid.

So, by this trace it seems `[(a=0)]=1` is indeed illegal because `a=1` is not  vald. Do you agree with this trace, @donnagf ?

Note that `[(a)]=1` would be legal because in the same trace, the identifier is a valid simple assignment target. ZeParser will accept that program, just like all the other parsers.

If you agree with this trace then it may be worth it to report to Babel and Esprima that they're incorrectly accepting `[(a=0)]=1`.

cc @RReverser what do you think?

**Comment by pvdz** [comment]
I fixed compound assignment not checking object/array literals in 972894e

**Comment by donnagf** [comment]
Great work! Sorry late reply. I had to keep an eye on my kids :) Anyway I was playing around with your code and found a few more programs that you could look into. As seen in [AST Explorer](https://astexplorer.net/#/gist/da9be626a056c5d5a12f86deeb80e49f/1323fb3884fe061dd0738ff72b6caba648545cee) ZeParser throws on valid code I guess.

```js
// Invalid
([{a: b.c}]) => d
([{a: b.c}] = a) => d
([{a: b.c} = a]) => d
{...{x} }
{...[x] }

// valid?
[((((a)))), b] = [];
[...[{prop: 1}.prop]] = []
({ a: {prop: 1}.prop } = {})

```

**Comment by donnagf** [comment]
@pvdz I think this is an edge case that should parse - `({ a: (b) = foo } = {})` ?

**Comment by pvdz** [comment]
Yes, that let's track that in #2.

I've pushed a bunch of changes (basically reverting a dubious diff) which created more stability. There's still many of these kinds of edge cases that are troubling. (And the diff briefly adds a bunch of TODOs so that I know what tests are still left to write to cover them)

// Invalid
- [x] `([{a: b.c}]) => d`
- [x] `([{a: b.c}] = a) => d`
- [x] `([{a: b.c} = a]) => d`
- [ ] `({...{x} }) => {}`
- [ ] `({...[x] }) => {}`

// valid?
- [ ] `[((((a)))), b] = [];`
- [ ] `[...[{prop: 1}.prop]] = []`
- [ ] `({ a: {prop: 1}.prop } = {})`

This is great! Please feel free to post new issues for separate bugs. I'll confirm them and try to fix them where necessary.

**Comment by pvdz** [comment]
Fixed a bug allowing non-idents in object spread in param destructuring in a0ae02e39a190863f50499ddf5ae384a7d1f70af, which solves two more cases here :)

**Comment by pvdz** [comment]
Oh and it seems I've also resolved the `[...[{prop: 1}.prop]] = []` cases so it seems to me like all things in this issue have been resolved.

Thanks for reporting them. Please do open new issues if you find more trouble :)

**Comment by donnagf** [comment]
Sorry if I'm not responding quickly :) I'm trying to read up on the specs to try help you out, and also keep track on my kids. Single daddy after my wife died of cancer :(

I may open another issue for this, but I quickly mention that Object spread in general should reject destructuring if I understand things correctly.  I found this cases, but didn't have time to test them out with ZeParser

```js
// should all be invalid
"let {...obj1,} = foo"
"let {...obj1,a} = foo"
"let {...obj1,...obj2} = foo"
"let {...(obj)} = foo"
"let {...(a,b)} = foo"
"let {...{a,b}} = foo"
"let {...[a,b]} = foo"
"({...obj1,} = foo)"
"({...obj1,a} = foo)"
"({...obj1,...obj2} = foo)"
"({...(obj)} = foo)"
"({...(a,b)} = foo)"
"({...{a,b}} = foo)"
"({...[a,b]} = foo)"
"({...obj} = foo)"
"({...(obj)}) => {}"
"({...(a,b)}) => {}"
"({...{a,b}}) => {}"
"({...[a,b]}) => {}"
"({...obj}) => {}"

// Valid
"({a:b,...obj}) => {}"
"({...obj} = {}) => {}",
"({...(a,b),c})",
"({...a,b,c})"
```

**Comment by pvdz** [comment]
I'm sorry for your loss. Please prioritize your kids. I got two kids, I know how it is. Your input is appreciated but your kids need you more. This project will be fine :)

As for the destructuring, I'll go through the list. Some looks valid to me and some are invalid and I don't know what the parser does with them. Destructuring is such a complex mess :(

**Comment by pvdz** [comment]
> BTW! Do you plan to add location tracking?

FYI; Location tracking in the AST just landed. Lemme know if there are problems :)
